config/routes.rb
Rails.application.routes.draw do
  get "tasks", to: "tasks#index", as: :index
  get "tasks/new", to: "tasks#new"
  get "tasks/:id", to: "tasks#show", as: :task
  post "tasks", to: "tasks#create"
  get "tasks/:id/edit", to: "tasks#edit"
  patch "tasks/:id", to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end
  def show
    id = params[:id]
    @task = Task.find(id)
  end
  def new
    @task = Task.new
  end
  def create
    @task = Task.create(task_params)
    @task.save
    redirect_to task_path(@task)
  end
  def edit
    @task = Task.find(params[:id])
  end
  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to index_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>update a new task</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>
<%= link_to "Edit", tasks_path %>

app/views/tasks/index.html.erb
<h1>Les tasks</h1>
<% @tasks.each do |task| %>
  <h2><%= task.title %></h2>
  <h2><%= task.details %></h2>
  <%= link_to "See All", task_path(task.id) %>
  <%= link_to "Delete", task_path(task.id),
  method: :delete,
  data: {confirm: "Are you sure?" } %>
  <% end %>
  <br/><br/><br/>
  <%= link_to "Add a task", tasks_new_path %>

app/views/tasks/new.html.erb
<%= form_for (@task)  do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.id %> Title: <%= @task.title %></h1>
<p><%= @task.details %></p>
<%= link_to "Back", tasks_path %>